name: ruleta1
description: App para divertirte con intimos amigos

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.10.5 <=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_fortune_wheel: ^0.4.2
  provider: ^5.0.0
  flutter_launcher_icons: "^0.8.0"
  animated_background: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo3.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg